---
- name: Clone project
  local_action:
    module: git
    clone: yes
    update: yes
    repo: "{{ git_repo }}"
    dest: "../{{ dir_rsync_cache }}"
    version: "{{ branch }}"
    force: "true"
  register: head_hash
