version: '2'
services:
  dev_app:
    build: ./bin/priv/hello_elixir
    image: kx_widget
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - .:/app:rw
    environment:
      MIX_ENV: dev
      MIX_DEBUG: 0
      HTTP_PORT: 8080
      SSH_AUTH_SOCK: "/ssh-agent"
    command: bin/priv/entrypoint
