kind: Deployment
apiVersion: apps/v1
metadata:
  name: foo-app
  labels:
    app: foo
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: foo
    spec:
      containers:
      - name: foo-app
#        image: krzysztofmo/http-echo:v1
        image: hashicorp/http-echo:0.2.3
#        image: krzysztofmo/hello-elixir:v1
        env:
          - name: node_name
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        args:
          - "-text=$(node_name)"
  selector:
    matchLabels:
      app: foo
---
kind: Service
apiVersion: v1
metadata:
  name: foo-service
spec:
  selector:
    app: foo
  ports:
    # Default port used by the image
    - port: 5678
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: bar-app
  labels:
    app: bar
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: bar
    spec:
      containers:
        - name: bar-app
          image: hashicorp/http-echo:0.2.3
          args:
            - "-text=bar"
  selector:
    matchLabels:
      app: bar
---
kind: Service
apiVersion: v1
metadata:
  name: bar-service
spec:
  selector:
    app: bar
  type: NodePort
  ports:
    # Default port used by the image
    - port: 5678
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example-ingress
spec:
  rules:
    - http:
        paths:
          - path: /foo
            backend:
              serviceName: foo-service
              servicePort: 5678
          - path: /bar
            backend:
              serviceName: bar-service
              servicePort: 5678
          - path: /
            backend:
              serviceName: hello-elixir
              servicePort: 8080
---
