---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-elixir
  name: hello-elixir
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-elixir
  strategy: {}
  template:
    metadata:
      labels:
        app: hello-elixir
    spec:
      containers:
        - image: gcr.io/hello-elixir-278607/hello-elixir:v1
          imagePullPolicy: Always
          name: hello-elixir
          resources: {}
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: HOST
              value: hello.jackal.pw

#
#
#
#apiVersion: v1
#kind: Pod
#metadata:
#  name: hello-elixir
#  labels:
#    app.kubernetes.io/name: hello
#    app.kubernetes.io/instance: wordpress-abcxzy
#    app.kubernetes.io/version: "0.0.1"
#    app.kubernetes.io/component: application
#    app.kubernetes.io/part-of: kontomatik
#    app.kubernetes.io/managed-by: helm
#spec:
#  containers:
#    - name: hello-elixir-app
#      image: gcr.io/hello-elixir-278607/hello-elixir
#      ports:
#        - containerPort: 8080
