---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-elixir
  name: hello-elixir
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-elixir
  template:
    metadata:
      labels:
        app: hello-elixir
    spec:
      serviceAccountName: hello-elixir-sa
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app: hello-elixir
      containers:
#        - image: gcr.io/hello-elixir-278607/hello-elixir:v1
        - image: krzysztofmo/hello-elixir:v1
          imagePullPolicy: Always
          name: hello-elixir
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: HOST
#              value: localhost
              value: hello.jackal.pw
