---
kind: Service
apiVersion: v1
metadata:
  name: hello-elixir
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: hello-elixir
  type: NodePort
#  externalTrafficPolicy: Local
#  sessionAffinity: ClientIP


---
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: hello-elixir
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: hello-elixit
              servicePort: 8080