apiVersion: v1
kind: Service
metadata:
  name: hello-elixir
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: hello-elixir
  type: LoadBalancer
  externalTrafficPolicy: Local
  sessionAffinity: ClientIP
