---
- name: Clone project
  local_action:
    module: git
    clone: yes
    update: yes
    repo: "{{ git_repo }}"
    dest: "../{{ dir_rsync_cache }}"
    version: "{{ branch }}"
    force: "true"
  register: head_hash

- name: Set revision
  local_action:
    module: lineinfile
    path: ../{{ dir_rsync_cache }}/config/config.exs
    regexp: 'release:'
    line: 'release: "{{ head_hash.after }}"'
